# Tutorial da Biblioteca Numpy

### Operações com arrays

- Soma
- Subtração
- Multiplicação
- Divisão
- Multiplicação matricial

In [2]:
import numpy as np

In [3]:
# Criando um simples array
arr = np.arange(0,11)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr/arr

C:\Users\bgfar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
#Multiplicação matricial
np.dot(arr,arr)

385

### Reshape

Altera a quantidade de linhas e colunas, desde que a matriz resultante permaneça com a mesma quantidade de elemnetos da matriz original.    
Reshape (n_linhas, _n_cols)

In [9]:
arr = np.random.rand(5,5)
arr

array([[0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514],
       [0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529],
       [0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192],
       [0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806],
       [0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993]])

In [10]:
arr.reshape(1,25).shape

(1, 25)

### Adicionando ou removendo elementos do ndarray

In [11]:
# Crinado uma nova matriz
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Adicionando linhas**   
As matrizes devem ter o mesmo número de colunas

In [12]:
np.append(arr,arr2)

array([0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514,
       0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529,
       0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192,
       0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806,
       0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993,
       0.        , 1.        , 2.        , 3.        , 4.        ,
       5.        , 6.        , 7.        , 8.        , 9.        ])

**Adicionando colunas**   
As matrizes devem ter o mesmo número de linhas

In [13]:
arr2 = arr2.reshape(5,2)

In [14]:
np.append(arr,arr2,axis=1)

array([[0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514,
        0.        , 1.        ],
       [0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529,
        2.        , 3.        ],
       [0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192,
        4.        , 5.        ],
       [0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806,
        6.        , 7.        ],
       [0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993,
        8.        , 9.        ]])

**Inserindo elementos**

1. Inserindo constante

In [15]:
num = np.array(5)

In [16]:
np.insert(arr,1,num, axis=1) #Preenchendo a segunda coluna

array([[0.3702565 , 5.        , 0.46329944, 0.84597346, 0.10132312,
        0.07107514],
       [0.16058097, 5.        , 0.45343181, 0.03044026, 0.71604509,
        0.37457529],
       [0.27912283, 5.        , 0.16947874, 0.98189935, 0.25789297,
        0.37851192],
       [0.16259429, 5.        , 0.5435111 , 0.03650833, 0.79272537,
        0.45409806],
       [0.59572181, 5.        , 0.95430452, 0.24167941, 0.47460998,
        0.57193993]])

In [17]:
np.insert(arr, 3, num, axis=0) #Preenchendo a quarta linha

array([[0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514],
       [0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529],
       [0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192],
       [5.        , 5.        , 5.        , 5.        , 5.        ],
       [0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806],
       [0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993]])

2. Inserindo vetor

In [18]:
num = np.array([1,2,3])

In [19]:
# Quando o eixo não é informado, o comando faz um flatten na matrix e insere o vetor no décimo elemento
np.insert(arr,10,num)

array([0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514,
       0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529,
       1.        , 2.        , 3.        , 0.27912283, 0.16947874,
       0.98189935, 0.25789297, 0.37851192, 0.16259429, 0.5435111 ,
       0.03650833, 0.79272537, 0.45409806, 0.59572181, 0.95430452,
       0.24167941, 0.47460998, 0.57193993])

In [20]:
np.delete(arr, 2, axis=1) #deletando a terceira coluna

array([[0.3702565 , 0.46329944, 0.10132312, 0.07107514],
       [0.16058097, 0.45343181, 0.71604509, 0.37457529],
       [0.27912283, 0.16947874, 0.25789297, 0.37851192],
       [0.16259429, 0.5435111 , 0.79272537, 0.45409806],
       [0.59572181, 0.95430452, 0.47460998, 0.57193993]])

### Principais Atributos e Funções

- max()  / argmax()
- min()  / argmin()
- mean()
- std()
- ravel()
- flatten()
- sort()
- shuffle()

In [21]:
arr.max()

0.9818993543878769

In [22]:
arr.argmax()

12

In [23]:
arr.min()

0.03044025746977652

In [24]:
arr.argmin()

7

In [25]:
arr.mean()

0.4192639880978748

In [26]:
arr.std()

0.2748236282622311

**Diferenças entre ravel () e flatten ()**

- ravel ()
    - retorna apenas uma visualização do array original
    - a modificação no vetor de saída, tambem modifica a matriz original
    - ravel () é mais rápido que o flatten () e não ocupa espaço na memória
    
- flatten ()
     - retorna uma cópia da matriz original
     - a modificação no vetor de saída não altera a matriz original
     - flatten () é mais lento que o ravel () e ocupa espaço na memória

In [27]:
arr.ravel()

array([0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514,
       0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529,
       0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192,
       0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806,
       0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993])

In [31]:
arr.flatten()

array([0.16259429, 0.5435111 , 0.03650833, 0.79272537, 0.45409806,
       0.16058097, 0.45343181, 0.03044026, 0.71604509, 0.37457529,
       0.3702565 , 0.46329944, 0.84597346, 0.10132312, 0.07107514,
       0.27912283, 0.16947874, 0.98189935, 0.25789297, 0.37851192,
       0.59572181, 0.95430452, 0.24167941, 0.47460998, 0.57193993])

**Ordenação**

A ordenação de um ndarray pode ser feita de três formas utilizando o método **sort ()**:
    1. axis = None  Transforma a matriz em um vetor e ordena os elementos no menor para o maior
    2. axis = 0     Ordena as colunas do menor para o maior
    3. axis = 1     Ordena as linhas do menor para o maior

In [33]:
arr3 = np.random.randint(100,size=(5,5))
arr3

array([[29, 21, 97, 64, 35],
       [85, 80, 53, 35, 73],
       [83, 12, 44, 60, 20],
       [54, 41, 85, 10, 73],
       [ 0, 55,  6, 67, 47]])

In [36]:
np.sort(arr3, axis=None)

array([ 0,  6, 10, 12, 20, 21, 29, 35, 35, 41, 44, 47, 53, 54, 55, 60, 64,
       67, 73, 73, 80, 83, 85, 85, 97])

In [37]:
np.sort(arr3, axis=0)

array([[ 0, 12,  6, 10, 20],
       [29, 21, 44, 35, 35],
       [54, 41, 53, 60, 47],
       [83, 55, 85, 64, 73],
       [85, 80, 97, 67, 73]])

In [38]:
np.sort(arr3, axis=1)

array([[21, 29, 35, 64, 97],
       [35, 53, 73, 80, 85],
       [12, 20, 44, 60, 83],
       [10, 41, 54, 73, 85],
       [ 0,  6, 47, 55, 67]])

**Shuffle ()**

O método shuffle () realiza um embaralhamento dos elementos ao longo do primeiro eixo de uma matriz multidimensional

In [39]:
arr3_sort = np.sort(arr3, axis=None).reshape(5,5)
arr3_sort

array([[ 0,  6, 10, 12, 20],
       [21, 29, 35, 35, 41],
       [44, 47, 53, 54, 55],
       [60, 64, 67, 73, 73],
       [80, 83, 85, 85, 97]])

In [52]:
np.random.shuffle(arr3_sort)

In [53]:
arr3_sort

array([[ 0,  6, 10, 12, 20],
       [80, 83, 85, 85, 97],
       [60, 64, 67, 73, 73],
       [44, 47, 53, 54, 55],
       [21, 29, 35, 35, 41]])