# Tutorial da Biblioteca Numpy

In [1]:
import numpy as np

In [2]:
# Criando um simples array
arr = np.arange(0,11)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr/arr

C:\Users\bgfar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
#Multiplicação matricial
np.dot(arr,arr)

385

### Reshape

In [81]:
arr = np.random.rand(5,5)
arr

array([[0.15129878, 0.88146812, 0.99744187, 0.02397822, 0.40952795],
       [0.01548566, 0.34200886, 0.55767021, 0.03562067, 0.32555282],
       [0.79021081, 0.61767054, 0.06201647, 0.52449293, 0.31433487],
       [0.0614879 , 0.00283053, 0.49084763, 0.63004423, 0.99196866],
       [0.68265705, 0.11164038, 0.42644919, 0.91324105, 0.24928185]])

In [80]:
arr.reshape(1,25).shape

(1, 25)

### Adicionando ou removendo elementos do ndarray

In [26]:
# Crinado uma nova matriz
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Adicionando linhas**   
As matrizes devem ter o mesmo número de colunas

In [18]:
np.append(arr,arr2)

array([0.85051608, 0.04065144, 0.4760942 , 0.8271763 , 0.24720026,
       0.97385729, 0.95629491, 0.93566257, 0.49373307, 0.22347112,
       0.40093978, 0.87381702, 0.90637742, 0.59675687, 0.28423589,
       0.33077822, 0.89958811, 0.90965318, 0.39576621, 0.39591131,
       0.42142999, 0.22533982, 0.89972757, 0.50653992, 0.7159289 ,
       0.        , 1.        , 2.        , 3.        , 4.        ,
       5.        , 6.        , 7.        , 8.        , 9.        ])

**Adicionando colunas**   
As matrizes devem ter o mesmo número de linhas

In [73]:
arr2 = arr2.reshape(5,2)

In [39]:
np.append(arr,arr2,axis=1)

array([[0.02333344, 0.0122683 , 0.35679572, 0.52378216, 0.55056427,
        0.        , 1.        ],
       [0.69764012, 0.77777181, 0.45803744, 0.92100401, 0.23408926,
        2.        , 3.        ],
       [0.14333916, 0.16048168, 0.11482062, 0.21961559, 0.9999387 ,
        4.        , 5.        ],
       [0.50586923, 0.21043387, 0.49912969, 0.9658327 , 0.24750694,
        6.        , 7.        ],
       [0.07832942, 0.88966797, 0.94045879, 0.08003223, 0.67936044,
        8.        , 9.        ]])

**Inserindo elementos**

1. Inserindo constante

In [84]:
num = np.array(5)

In [86]:
np.insert(arr,1,num, axis=1) #Preenchendo a segunda coluna

array([[1.51298777e-01, 5.00000000e+00, 8.81468117e-01, 9.97441874e-01,
        2.39782249e-02, 4.09527950e-01],
       [1.54856551e-02, 5.00000000e+00, 3.42008861e-01, 5.57670213e-01,
        3.56206688e-02, 3.25552818e-01],
       [7.90210812e-01, 5.00000000e+00, 6.17670536e-01, 6.20164734e-02,
        5.24492933e-01, 3.14334874e-01],
       [6.14878992e-02, 5.00000000e+00, 2.83052843e-03, 4.90847633e-01,
        6.30044227e-01, 9.91968658e-01],
       [6.82657051e-01, 5.00000000e+00, 1.11640380e-01, 4.26449189e-01,
        9.13241046e-01, 2.49281849e-01]])

In [87]:
np.insert(arr, 3, num, axis=0) #Preenchendo a quarta linha

array([[1.51298777e-01, 8.81468117e-01, 9.97441874e-01, 2.39782249e-02,
        4.09527950e-01],
       [1.54856551e-02, 3.42008861e-01, 5.57670213e-01, 3.56206688e-02,
        3.25552818e-01],
       [7.90210812e-01, 6.17670536e-01, 6.20164734e-02, 5.24492933e-01,
        3.14334874e-01],
       [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, 5.00000000e+00,
        5.00000000e+00],
       [6.14878992e-02, 2.83052843e-03, 4.90847633e-01, 6.30044227e-01,
        9.91968658e-01],
       [6.82657051e-01, 1.11640380e-01, 4.26449189e-01, 9.13241046e-01,
        2.49281849e-01]])

2. Inserindo vetor

In [67]:
num = np.array([1,2,3])

In [75]:
# Quando o eixo não é informado, o comando faz um flatten na matrix e insere o vetor no décimo elemento
np.insert(arr,10,num)

array([0.02333344, 0.0122683 , 0.35679572, 0.52378216, 0.55056427,
       0.69764012, 0.77777181, 0.45803744, 0.92100401, 0.23408926,
       1.        , 2.        , 3.        , 0.14333916, 0.16048168,
       0.11482062, 0.21961559, 0.9999387 , 0.50586923, 0.21043387,
       0.49912969, 0.9658327 , 0.24750694, 0.07832942, 0.88966797,
       0.94045879, 0.08003223, 0.67936044])

In [88]:
np.delete(arr, 2, axis=1) #deletando a terceira coluna

array([[0.15129878, 0.88146812, 0.02397822, 0.40952795],
       [0.01548566, 0.34200886, 0.03562067, 0.32555282],
       [0.79021081, 0.61767054, 0.52449293, 0.31433487],
       [0.0614879 , 0.00283053, 0.63004423, 0.99196866],
       [0.68265705, 0.11164038, 0.91324105, 0.24928185]])

### Principais Atributos e Funções

- max()  / argmax()
- min()  / argmin()
- mean()
- std()
- ravel()
- flatten()
- sort()
- shuffle()

In [89]:
arr.max()

0.9974418738575519

In [90]:
arr.argmax()

2

In [91]:
arr.min()

0.0028305284300740308

In [92]:
arr.argmin()

16

In [93]:
arr.mean()

0.4243690899203545

In [94]:
arr.std()

0.3201345875517597

In [95]:
arr.ravel()

array([0.15129878, 0.88146812, 0.99744187, 0.02397822, 0.40952795,
       0.01548566, 0.34200886, 0.55767021, 0.03562067, 0.32555282,
       0.79021081, 0.61767054, 0.06201647, 0.52449293, 0.31433487,
       0.0614879 , 0.00283053, 0.49084763, 0.63004423, 0.99196866,
       0.68265705, 0.11164038, 0.42644919, 0.91324105, 0.24928185])

In [96]:
arr.flatten()

array([0.15129878, 0.88146812, 0.99744187, 0.02397822, 0.40952795,
       0.01548566, 0.34200886, 0.55767021, 0.03562067, 0.32555282,
       0.79021081, 0.61767054, 0.06201647, 0.52449293, 0.31433487,
       0.0614879 , 0.00283053, 0.49084763, 0.63004423, 0.99196866,
       0.68265705, 0.11164038, 0.42644919, 0.91324105, 0.24928185])

In [98]:
np.sort(arr,axis=0)

array([[0.01548566, 0.00283053, 0.06201647, 0.02397822, 0.24928185],
       [0.0614879 , 0.11164038, 0.42644919, 0.03562067, 0.31433487],
       [0.15129878, 0.34200886, 0.49084763, 0.52449293, 0.32555282],
       [0.68265705, 0.61767054, 0.55767021, 0.63004423, 0.40952795],
       [0.79021081, 0.88146812, 0.99744187, 0.91324105, 0.99196866]])

In [101]:
np.random.shuffle(arr)
arr

array([[0.15129878, 0.88146812, 0.99744187, 0.02397822, 0.40952795],
       [0.01548566, 0.34200886, 0.55767021, 0.03562067, 0.32555282],
       [0.79021081, 0.61767054, 0.06201647, 0.52449293, 0.31433487],
       [0.0614879 , 0.00283053, 0.49084763, 0.63004423, 0.99196866],
       [0.68265705, 0.11164038, 0.42644919, 0.91324105, 0.24928185]])