# Tutorial Numpy

## Este tutorial compreende:

- Criação de numpy arrays
- Indexação
- Atribuição e transmissão
- Principais métodos 
- Operações com arrays
- Alterando dimensões
- Inserindo elementos


**Importando Biblioteca**

In [2]:
import numpy as np

### Criação de numpy arrays

**Método np.arange()**

Retorna um numpy array com elementos igualmente espaçados dentro do intervalo especificado.    
É possível criar diferentes tipos de numpy array, como float, 'int64', 'int16', etc...

In [9]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Método np.linspace()**

Retorna um numpy array com a quantidade de elementos descritos no último parâmetro

In [10]:
ar2 = np.linspace(0,15,3)
ar2

array([ 0. ,  7.5, 15. ])

**Método np.zeros()**

Cria uma matriz de zeros. O primeiro parâmetro é a quantidade de linhas e o segundo a quantidade de colunas da matriz.

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Método np.ones()**

Cria uma matriz de uns. O primeiro parâmetro é a quantidade de linhas e o segundo a quantidade de colunas da matriz.   
Ps.: A partir da matriz de uns é possível criar uma matriz de qualquer outro número real.

In [16]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((3,5))*8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

**Criando uma matriz identidade**

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Criando o seu próprio Array**

In [19]:
my_array = np.array([[4,6,5],[7,9,10],[1,2,3]])

In [20]:
my_array

array([[ 4,  6,  5],
       [ 7,  9, 10],
       [ 1,  2,  3]])

**Criando um array a patir de uma lista**

In [21]:
my_list = [1,3,5,9,7,4]

my_array_ = np.array(my_list)

In [25]:
my_array_

array([1, 3, 5, 9, 7, 4])

**Criação de arrays randômicos**

**Método Rand**

Cria uma matriz com amostras aleatórias em distribuição uniforme sobre [0,1).

In [26]:
np.random.rand(3,3)

array([[0.55397742, 0.34344999, 0.04556172],
       [0.76477971, 0.49737612, 0.77964878],
       [0.18171235, 0.37538487, 0.84793906]])

**Método Randn**

Cria um matriz de distribuição normal.

In [27]:
np.random.randn(3,3)

array([[ 0.53157939,  1.90977831, -0.38423145],
       [-1.34852077, -2.32237459, -0.16395453],
       [ 0.88155652, -0.09132238,  0.76232368]])

**Método Randint**

Dado um intervalo, o método retorna um inteiro aleatório a partir do low (inclusivo) e do  high (exclusivo).

In [29]:
np.random.randint(5,90)

69

In [39]:
np.random.randint(9,100, size=(4,4))

array([[31, 66, 10,  9],
       [69, 90, 17, 97],
       [22, 56, 81, 39],
       [80, 12, 79, 30]])

**Método Seed**

Cria uma matriz de números aleatórios fixa. Este comando é utilizado quando é necessário um conjunto de valores aleatórios fixo.

In [66]:
np.random.seed(1)
np.random.randint(9,100, size=(4,4))

array([[46, 21, 81, 18],
       [84, 14, 88, 73],
       [25, 10, 85, 80],
       [15, 34, 59, 29]])

### Indexação

Indexação é a forma como um ou mais elementos são selecionados dentro de uma matriz de arrays.

In [69]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [71]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

A indexação é em um array unidimensional feita entre colchetes, em que o número corresponde a posição do elemento.   
A primeira posição corresponde ao índice 0.

In [73]:
arr[5]

6

In [76]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [112]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Selecionando apenas um elemento da matriz

In [114]:
arr2[2][1]

8

Para selecionar um elemento de uma matriz, é necessário informar a posição da linha e da coluna.

In [78]:
arr2[2,1]

8

Para selecionar mais de um elemento é preciso informar o intervalo.

In [102]:
arr3 = np.array([[1,7,3,5,9,11],[2,4,6,8,10,12], [1,2,3,5,7,11],[13,17,19,23,29,31]])
arr3

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

In [81]:
arr3[1:3,2:4]

array([[6, 8],
       [3, 5]])

Para selecionar todos os elementos de um eixo, basta utilizar    <span style="color:red">**:**</span> 

In [82]:
arr3[:,:4]

array([[ 1,  7,  3,  5],
       [ 2,  4,  6,  8],
       [ 1,  2,  3,  5],
       [13, 17, 19, 23]])

In [83]:
# Selecionando toda a matriz
arr3[:]

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

### Atribuição e Transmissão

In [103]:
arr3

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

In [104]:
arr3[:3,:3] = 100
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100,   5,   7,  11],
       [ 13,  17,  19,  23,  29,  31]])

In [105]:
slice_arr3 = arr3[2:,3:5]
slice_arr3

array([[ 5,  7],
       [23, 29]])

In [106]:
slice_arr3[:] = 222

In [107]:
slice_arr3

array([[222, 222],
       [222, 222]])

In [108]:
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100, 222, 222,  11],
       [ 13,  17,  19, 222, 222,  31]])

O valor alterado da fatia (slice_arr3) tambem está alterando a matriz original. Para impedir isso é utilizado o método **.copy()**

In [109]:
arr_copy = arr3[:,1:4].copy()
arr_copy

array([[100, 100,   5],
       [100, 100,   8],
       [100, 100, 222],
       [ 17,  19, 222]])

In [110]:
arr_copy[:] = 55
arr_copy

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [111]:
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100, 222, 222,  11],
       [ 13,  17,  19, 222, 222,  31]])