# Tutorial Numpy 

## Este Tutorial Compreende:

- Tamanho e Dimensões
- Principais métodos 
- Operações com arrays

### Tamanho e Dimensões

Existem diferentes formas de checar o tamanho e dimensão de um numpy array:
- **.itemsize**
- **.size**
- **.shape**
- **ndim**

In [2]:
import numpy as np

In [13]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]], dtype='int32')

**O atributo *.itemsize* retorna o tamnaho de cada item do array em bits. 
Neste caso cada item ocupa 4 bits na memória, ou seja, metade de um byte.**

In [12]:
arr.itemsize

4

**O atributo *.size* retorna a quantidade de elementos de um array.**

In [15]:
arr.size

12

**O atributo *.shape* retorna uma tupla com a quantidade de linhas e colunas, respectivamente**

In [16]:
arr.shape

(4, 3)

**O atributo *ndim* retorna a quantidade de dimensões do array**

In [17]:
arr.ndim

2

### Principais Métodos

- mean()
- max() / argmax()
- min() / argmin()
- std()
- ravel()
- flatten()

In [23]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr.mean()

6.5

In [26]:
arr.max()

12

In [27]:
arr.argmax() #retorna o indice do maior valor

11

In [28]:
arr.min()

1

In [29]:
arr.argmin()

0

In [36]:
arr.std() #desvio padrão

3.452052529534663

**O método *ravel()* transforma um array n-dimensional para um array unidimensional**

In [39]:
arr_ravel = arr.ravel()
arr_ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**O método *flatten()* transforma um array n-dimensional para um array unidimensional**

In [40]:
arr_flatten = arr.flatten()
arr_flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

As diferenças entre ravel() e flatten()

**ravel()**
- Retorna apenas uma visulaização do array original
- Se for feita alguma modificação no array, tambem irá modificar o array original
- É mais rápido que o flatten e não ocupa espaço na memória

**flatten()**
- Retorna uma cópia do array original
- Se for feita alguma modificação no array, não irá modificar o array original
- É mais lento que o ravel e ocupa espaço na memória

### Operações com arrays

- Soma
- Subtração
- Multiplicação
- Multiplicação Matricial
- Divisão

In [42]:
array_a = np.random.randint(100, size=(7,7))

In [43]:
array_a

array([[40, 81, 28, 18, 47, 53,  1],
       [60, 30, 57, 85,  0, 20, 54],
       [80, 68, 80, 26, 22,  1, 47],
       [83, 24, 17, 74, 21, 97, 94],
       [11, 96, 76, 64, 75, 85, 55],
       [10, 73, 43, 97, 10, 98,  9],
       [38, 44, 21, 46, 76, 35, 75]])

In [44]:
array_b = np.random.randint(100,size=(7,7))

In [45]:
array_b

array([[32, 50, 59, 74, 60, 34, 94],
       [35, 77, 62, 96, 84, 91, 54],
       [81, 81, 92,  1,  6, 45, 23],
       [27, 96, 27, 93, 86, 57, 88],
       [92, 51, 25, 72, 72, 26, 49],
       [77, 30, 69, 76, 92, 47,  6],
       [67, 11, 76, 22, 85, 90, 98]])

In [46]:
array_a+array_b

array([[ 72, 131,  87,  92, 107,  87,  95],
       [ 95, 107, 119, 181,  84, 111, 108],
       [161, 149, 172,  27,  28,  46,  70],
       [110, 120,  44, 167, 107, 154, 182],
       [103, 147, 101, 136, 147, 111, 104],
       [ 87, 103, 112, 173, 102, 145,  15],
       [105,  55,  97,  68, 161, 125, 173]])

In [47]:
array_a-array_b

array([[  8,  31, -31, -56, -13,  19, -93],
       [ 25, -47,  -5, -11, -84, -71,   0],
       [ -1, -13, -12,  25,  16, -44,  24],
       [ 56, -72, -10, -19, -65,  40,   6],
       [-81,  45,  51,  -8,   3,  59,   6],
       [-67,  43, -26,  21, -82,  51,   3],
       [-29,  33, -55,  24,  -9, -55, -23]])

In [48]:
array_a*array_b

array([[1280, 4050, 1652, 1332, 2820, 1802,   94],
       [2100, 2310, 3534, 8160,    0, 1820, 2916],
       [6480, 5508, 7360,   26,  132,   45, 1081],
       [2241, 2304,  459, 6882, 1806, 5529, 8272],
       [1012, 4896, 1900, 4608, 5400, 2210, 2695],
       [ 770, 2190, 2967, 7372,  920, 4606,   54],
       [2546,  484, 1596, 1012, 6460, 3150, 7350]])

In [49]:
np.dot(array_a,array_b) # Multiplicação de matrizes

array([[15341, 16231, 15352, 19872, 19265, 14820, 13081],
       [15040, 19281, 18423, 17990, 20202, 17980, 21463],
       [17372, 19881, 21189, 17640, 18899, 18839, 21010],
       [22570, 19494, 24309, 26297, 31888, 23554, 26824],
       [28726, 27222, 27241, 29128, 32579, 27073, 23173],
       [18046, 22465, 19387, 25178, 25833, 20123, 16367],
       [20411, 17156, 18159, 21117, 25125, 19234, 21763]])

In [50]:
array_a/array_b

array([[1.25000000e+00, 1.62000000e+00, 4.74576271e-01, 2.43243243e-01,
        7.83333333e-01, 1.55882353e+00, 1.06382979e-02],
       [1.71428571e+00, 3.89610390e-01, 9.19354839e-01, 8.85416667e-01,
        0.00000000e+00, 2.19780220e-01, 1.00000000e+00],
       [9.87654321e-01, 8.39506173e-01, 8.69565217e-01, 2.60000000e+01,
        3.66666667e+00, 2.22222222e-02, 2.04347826e+00],
       [3.07407407e+00, 2.50000000e-01, 6.29629630e-01, 7.95698925e-01,
        2.44186047e-01, 1.70175439e+00, 1.06818182e+00],
       [1.19565217e-01, 1.88235294e+00, 3.04000000e+00, 8.88888889e-01,
        1.04166667e+00, 3.26923077e+00, 1.12244898e+00],
       [1.29870130e-01, 2.43333333e+00, 6.23188406e-01, 1.27631579e+00,
        1.08695652e-01, 2.08510638e+00, 1.50000000e+00],
       [5.67164179e-01, 4.00000000e+00, 2.76315789e-01, 2.09090909e+00,
        8.94117647e-01, 3.88888889e-01, 7.65306122e-01]])