# Tutorial Numpy

## Este tutorial compreende:

- Criação de numpy arrays
- Indexação
- Atribuição e transmissão

**Importando Biblioteca**

In [2]:
import numpy as np

### Criação de numpy arrays

**Método np.arange()**

Retorna um numpy array com elementos igualmente espaçados dentro do intervalo especificado.    
É possível criar diferentes tipos de numpy array, como float, 'int64', 'int16', etc...

In [3]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Método np.linspace()**

Retorna um numpy array com a quantidade de elementos descritos no último parâmetro

In [4]:
ar2 = np.linspace(0,15,3)
ar2

array([ 0. ,  7.5, 15. ])

**Método np.zeros()**

Cria uma matriz de zeros. O primeiro parâmetro é a quantidade de linhas e o segundo a quantidade de colunas da matriz.

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Método np.ones()**

Cria uma matriz de uns. O primeiro parâmetro é a quantidade de linhas e o segundo a quantidade de colunas da matriz.   
Ps.: A partir da matriz de uns é possível criar uma matriz de qualquer outro número real.

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((3,5))*8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

**Criando uma matriz identidade**

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Criando o seu próprio Array**

In [9]:
my_array = np.array([[4,6,5],[7,9,10],[1,2,3]])

In [43]:
my_array

array([[ 4,  6,  5],
       [ 7,  9, 10],
       [ 1,  2,  3]])

**Criando um array a patir de uma lista**

In [11]:
my_list = [1,3,5,9,7,4]

my_array_ = np.array(my_list)

In [12]:
my_array_

array([1, 3, 5, 9, 7, 4])

Por default um array é do tipo 'int64' se estiver alocado em uma máquina de 64-bits.
É possível alterar o tipo do array através do atributo *dtype*

In [47]:
my_array.dtype

dtype('int32')

In [48]:
my_arr_float = my_array.astype(np.float32)

In [49]:
my_arr_float.dtype

dtype('float32')

**Criação de arrays randômicos**

**Método Rand**

Cria uma matriz com amostras aleatórias em distribuição uniforme sobre [0,1).

In [13]:
np.random.rand(3,3)

array([[0.18897792, 0.78986002, 0.37947973],
       [0.46336155, 0.08748804, 0.20134382],
       [0.9669466 , 0.14261334, 0.30088805]])

**Método Randn**

Cria um matriz de distribuição normal.

In [14]:
np.random.randn(3,3)

array([[ 0.44221233,  0.03465867,  0.49001158],
       [ 0.36252988, -0.27355128, -0.12474072],
       [-1.41083272,  2.00032313, -1.3411473 ]])

**Método Randint**

Dado um intervalo, o método retorna um inteiro aleatório a partir do low (inclusivo) e do  high (exclusivo).

In [15]:
np.random.randint(5,90)

64

In [16]:
np.random.randint(9,100, size=(4,4))

array([[28, 52, 92, 83],
       [83, 89, 34, 81],
       [23, 47, 70, 73],
       [10, 95, 32, 55]])

**Método Seed**

Cria uma matriz de números aleatórios fixa. Este comando é utilizado quando é necessário um conjunto de valores aleatórios fixo.

In [17]:
np.random.seed(1)
np.random.randint(9,100, size=(4,4))

array([[46, 21, 81, 18],
       [84, 14, 88, 73],
       [25, 10, 85, 80],
       [15, 34, 59, 29]])

### Indexação

Indexação é a forma como um ou mais elementos são selecionados dentro de uma matriz de arrays.

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

A indexação é em um array unidimensional feita entre colchetes, em que o número corresponde a posição do elemento.   
A primeira posição corresponde ao índice 0.

In [20]:
arr[5]

6

In [21]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [22]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Selecionando apenas um elemento da matriz

In [23]:
arr2[2][1]

8

Para selecionar um elemento de uma matriz, é necessário informar a posição da linha e da coluna.

In [24]:
arr2[2,1]

8

Para selecionar mais de um elemento é preciso informar o intervalo.

In [25]:
arr3 = np.array([[1,7,3,5,9,11],
                 [2,4,6,8,10,12],
                 [1,2,3,5,7,11],
                 [13,17,19,23,29,31]])
arr3

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

In [26]:
arr3[1:3,2:4]

array([[6, 8],
       [3, 5]])

Para selecionar todos os elementos de um eixo, basta utilizar    <span style="color:red">**:**</span> 

In [27]:
arr3[:,:4]

array([[ 1,  7,  3,  5],
       [ 2,  4,  6,  8],
       [ 1,  2,  3,  5],
       [13, 17, 19, 23]])

In [28]:
# Selecionando toda a matriz
arr3[:]

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

### Atribuição e Transmissão

In [29]:
arr3

array([[ 1,  7,  3,  5,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29, 31]])

In [30]:
arr3[:3,:3] = 100
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100,   5,   7,  11],
       [ 13,  17,  19,  23,  29,  31]])

In [31]:
slice_arr3 = arr3[2:,3:5]
slice_arr3

array([[ 5,  7],
       [23, 29]])

In [32]:
slice_arr3[:] = 222

In [33]:
slice_arr3

array([[222, 222],
       [222, 222]])

In [34]:
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100, 222, 222,  11],
       [ 13,  17,  19, 222, 222,  31]])

O valor alterado da fatia (slice_arr3) tambem está alterando a matriz original. Para impedir isso é utilizado o método **.copy()**

In [35]:
arr_copy = arr3[:,1:4].copy()
arr_copy

array([[100, 100,   5],
       [100, 100,   8],
       [100, 100, 222],
       [ 17,  19, 222]])

In [36]:
arr_copy[:] = 55
arr_copy

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [37]:
arr3

array([[100, 100, 100,   5,   9,  11],
       [100, 100, 100,   8,  10,  12],
       [100, 100, 100, 222, 222,  11],
       [ 13,  17,  19, 222, 222,  31]])